name: gaussian_splatting
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - tqdm
  - plyfile
  - pip:
      - opencv-python
      - joblib
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
      - submodules/fused-ssim
